### ISSUE TITLE
ggmcmc to entail justSample for MCMC and incremental

### ISSUE THREAD

**Issue by mhtess** [mhtess/rwebppl#15]
For inference techniques MCMC and IncrementalMH, the `justSample = true` argument means that `Infer` will return a delta distribution at the `MAP` with a property called `samples`. `myDist.samples` returns an array of samples in the order they were collected. each sample is a json object with `value` and `score` properties (we can throw away score)

By using the `justSample` option, we can appropriately assign Iteration numbers to samples, which is useful for various `ggmcmc` visualizations

**Comment by mhtess** [comment]
It doesn't need to default actually. We can just look for that option in the inference_opts and handle it appropriately.

**Comment by mhtess** [comment]
I think this commit broke something:

```
myFirstModel <- '
// Unpack data
var k = 5 // number of heads
var n = 10

var model = function() {
   var p = uniform( {a:0, b:1} )

   factor(Binomial( {p : p, n: n }).score(k))

   return {p: p}
}
Infer({method:"rejection", samples:1000}, model)
'


webppl(myFirstModel)
```

returns 

```
Error in rep.int(seq_len(nrow(df)), times = round(df$prob * num_samples)) : 
  object 'num_samples' not found
```

Same behavior with `MCMC`

**Comment by mhtess** [comment]
FWIW, `justSample` only works with incrementalMH and MCMC

**Comment by mikabr** [comment]
good now?

**Comment by mhtess** [comment]
Seems to have done the trick. I wonder if `rejection` should always return just the samples, because that is basically what it is doing. This can be a separate issue.
