### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by hawkrobe** [mhtess/rwebppl#20]
Consider this model, which samples a value `p`, does something completely irrelevant with it, then returns `p`. 

```
testModel <- '
var n = 15
var model = function() {
   var p = uniform( {a:0, b:1} )    // sample a coin weight from a uniform distribution
   var totallyIrrelevantGarbage = sample(Binomial({p : p, n : n}))
   return {p : p};
}
'

webppl(
    program_code = testModel,
    inference_opts = list(method="MCMC", samples = 100000, burn = 5000),
    ggmcmc = TRUE,
    model_var = "model"
    ) %>%
  ggs_histogram()
```

There's no factor statements, so you'd expect the posterior to look like the prior: a uniform distribution over [0,1]. Instead, the result is skewed toward `p = 1`.

If you delete `totallyIrrelevantGarbage`, you recover the expected distribution.

A little playing around showed that this isn't a problem in vanilla command-line webppl, and that it's still a problem if you externally pass in the data via `data_var`. 

We also see that this is only a problem if you pass in the `p` sampled above, e.g. this works just fine:

```
testModel <- '
var n = 15
var model = function() {
   var p = uniform( {a:0, b:1} )    // sample a coin weight from a uniform distribution
   var totallyIrrelevantGarbage = sample(Binomial({p : .5, n : n}))
   return {p : p};
}
'
```

Seems like something is happening behind the scenes that's mutating p or polluting the namespace in a way that's overshadowing it.

**Comment by mhtess** [comment]
What happens is you remove all the other `p`'s from the program? (using shorthand syntax like `binomial(p, n)`)?

**Comment by hawkrobe** [comment]
doesn't look like that changes the output. 

![image](https://cloud.githubusercontent.com/assets/5262024/15982272/346d957e-2f38-11e6-980a-5a09447f3150.png)

Also of interest: it seems to be limited to the binomial distribution. Changing `totallyIrrelevantGarbage` to `flip(p)` or `gaussian(p, 1)` or `uniform(p,1)` doesn't have the same problem.

**Comment by hawkrobe** [comment]
Note that this issue isn't resolved by removing the `ggmcmc` option:

```
testModel <- '
var n = 15
var model = function() {
   var p = uniform( {a:0, b:1} )    // sample a coin weight from a uniform distribution
   var totallyIrrelevantGarbage = sample(Binomial({p : p, n : n}))
   return {p : p};
}
'

get_samples(webppl(
    program_code = testModel,
    inference_opts = list(method="MCMC", samples = 100000, burn = 5000),
    model_var = "model"
    ), num_samples = 100000) %>%
  ggplot(aes(x = p)) +
  geom_histogram()
```

![image](https://cloud.githubusercontent.com/assets/5262024/16017540/3821c928-3155-11e6-8eac-fbdef6dcdd30.png)

**Comment by mhtess** [comment]
This is an issue with big papa WebPPL
