### ISSUE TITLE
use uid for all temp files

### ISSUE THREAD

**Issue by hawkrobe** [mhtess/rwebppl#44]
`output_file` and `finish_file` are generated with a new uid every run, but `error_file` needs to be cleaned and rewritten every time. If we also created `error_file` with a uid, we wouldn't need to do [all this cleaning](https://github.com/mhtess/rwebppl/blob/master/R/rwebppl.R#L343-L356).

**Comment by hawkrobe** [comment]
@mikabr @mhtess : I was cleaning this up and noticed that the `program_file` is generated via `tempfile()` (which looks like it puts it somewhere in `/var` by default. But the others are created in `/tmp` with a UID. Is there a reason they couldn't all be put in `/tmp` with that UID?

**Comment by mikabr** [comment]
I don't remember the exact reason, I think it was something about all the files originally being created with `tempfile()`, but then we wanted some uniqueness guarantees for some of them? I think doing them all the same way in `/tmp` seems like a good idea.

**Comment by hawkrobe** [comment]
Closed by #54
