### ISSUE TITLE
Yoke rwebppl versions to particular webppl versions

### ISSUE THREAD

**Issue by mhtess** [mhtess/rwebppl#50]
This may only make sense going forward, but it would be good to yoke RWebPPL versions to versions of WebPPL. That way, if we have rwebppl in packrat, others can deploy the same version of webppl we were using..

**Comment by mhtess** [comment]
- Always install local version of webppl from rwebppl.json
- Have option for installing versions of webppl other than the npm version

**Comment by mikabr** [comment]
- [x] `install_webppl()` takes argument(s) specifying webppl version (including dev versions from a commit), passes them to `install_webppl.sh` call
- [x] `install_webppl.sh` uses that to modify `rwebppl.json` before calling `npm install`
- [x] webppl version is specified in package metadata, passed to `install_webppl()`

**Comment by mhtess** [comment]
This would probably address #42

**Comment by mikabr** [comment]
- [x] support dev version of webppl
- [x] remove deprecated symlinking code
- [x] update `README`

**Comment by mhtess** [comment]
Addressed by PR #53
