### ISSUE TITLE
Make install files executable

### ISSUE THREAD

**Issue by smihael** [mhtess/rwebppl#59]
Using Ubuntu 16.04 and R 4.3.4, I get the following error when running 

> devtools::install_github("mhtess/rwebppl")

```
Downloading GitHub repo mhtess/rwebppl@master
from URL https://api.github.com/repos/mhtess/rwebppl/zipball/master
Installing rwebppl
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  'TMP_PATH' --library='PATH_TO_R' --install-tests 

* installing *source* package ‘rwebppl’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
installing webppl ...sh: 1: PATH_TO_R/rwebppl/bash/install-webppl.sh: Permission denied
sh: 1:PATH_TO_R/rwebppl/bash/rearrange-webppl.sh: Permission denied
 done
Warning in get_webppl_version() : couldn't find local webppl install
* DONE (rwebppl)
```

I've hidden my local paths for privacy reasons.

The problem consists because by default the files downloaded from github are not set as executable (`chmod +x` solves that).

**Comment by hawkrobe** [comment]
Thanks, @smihael! Finally got a chance to look at this. We have [fileMode](https://git-scm.com/docs/git-config#git-config-corefileMode) set to true in our config, so in principle git should be tracking the executable bit and downloading it with it on (in fact, I believe that's the only permissions bit that git tracks). So I'm not sure how that's being over-ridden on your system. But we added an additional `chmod +x` line to force permissions just in case! Can you check whether it works on your system after commit 1ead14672909dfe7eda4fbd6edacf0b76ed04458?
